BUG Not reaching code due to print statement
Remove a print statement with a get on a config class was causing
an exception when called with an none existent profile.

ConfigParser.NoSectionError: No section: 'profile sdasda'

Also moved some of the tests around as they didnt make sense in the
order specified.